PreScripds.UI/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageResizer;
using PreScripds.Domain;
using PreScripds.Infrastructure;
using PreScripds.UI.Common;
using PreScripds.UI.Models;

namespace PreScripds.UI.Controllers
{
    public class BaseController : Controller
    {
        public ViewResult AppSettings()
        {
            var appSettings = new AppSettingModel()
            {
                AppPath = GetAppPath()
            };
            return View(appSettings);
        }

        public string GetAppPath()
        {
            return Request.ApplicationPath == "/" ? Request.ApplicationPath : Request.ApplicationPath + "/";
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var cntxt = System.Web.HttpContext.Current;
            base.OnActionExecuting(filterContext);
        }

        public ActionResult CheckSessionContext(string returnUrl = "")
        {
            if (SessionContext.CurrentUser == null)
                return RedirectToAction("Login", "Account");
            else if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public LibraryAsset GetLibraryAsset(HttpPostedFileBase file, string userfileName = null, string userDesc = null, long? folderId = null)
        {
            var appFileSize = Constants.GetConfigValue<int>(Constants.ApplicationConstants.FILE_SIZE) * (1024 * 1024);
            var isFile = file != null;

            if (isFile)
            {
                if ((isFile && file.ContentLength > 0 && file.ContentLength <= appFileSize && file.FileName.IsNotEmpty()))
                {
                    var libraryAsset = new LibraryAsset();
                    string fileName = "";
                    int contentLength = 0;
                    string contentType = "";
                    byte[] array = null;
                    if (isFile)
                    {
                        if (userfileName == null)
                        {
                            fileName = Path.GetFileName(file.FileName);
                        }
                        else
                        {
                            var trimdUserFileName = userfileName.Replace(" ", string.Empty);
                            fileName = Path.GetFileName(trimdUserFileName);
                        }

                        contentLength = file.ContentLength;
                        contentType = file.ContentType;
                        array = file.ToByteArray();
                    }

                    libraryAsset.AssetThumbnail = ImageExtensions.ResizeImage(ImageExtensions.ByteArrayToImage(array), new Size(40, 40));
                    libraryAsset.AssetName = fileName;
                    libraryAsset.AssetSize = contentLength;
                    libraryAsset.AssetType = contentType;
                    libraryAsset.CreatedDate = DateTime.Now;
                    libraryAsset.AssetExtension = Path.GetExtension(file.FileName);
                    libraryAsset.AssetDescription = userDesc;
                    if (folderId.HasValue)
                        libraryAsset.LibraryFolderId = folderId.Value;
                    libraryAsset.AssetPath = ConfigurationManager.AppSettings["AppAssetPath"];
                    libraryAsset.Active = true;
                    libraryAsset.LibraryAssetFiles = new List<LibraryAssetFile>()
                            {
                                new LibraryAssetFile()
                                {
                                    Asset = array,
                                    CreatedDate = DateTime.Now
                                }
                            };

                    return libraryAsset;
                }
            }
            return null;
        }
    }
}

PreScripds.UI/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "AccessDenied";
    Layout = "~/Views/Shared/_OpenLayout.cshtml";
}

<link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">

<div class="row blackBg  error-page">
    <div class="col-md-2 col-sm-3">

        <img src="~/Images/resized_535dc721588b0.jpg" />
    </div>
    <div class="col-md-6 col-sm-12 pull-right">
        <div>The page you are looking for is no longer here. </div>
        <div>Go to our <a title="Login Page" href="@Url.Action("Login", "Account")">Login Page</a></div>
    </div>
</div>

PreScripds.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/favicon.ico">
    <title style="color: #1E5530">PreScripds</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div>
                    <a class="navbar-brand" href="@Url.Action("Index")">
                        <img src="~/Images/logo_532279_web.jpg" class="img-responsive" alt="prescripds" title="prescripds" />
                    </a>
                </div>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#Home" title="Home"><span class="glyphicon glyphicon-home" title="Home"></span></a></li>
                    <li><a href="#About" title="About"><span class="glyphicon glyphicon-map-marker" title="About"></span></a></li>
                    <li><a href="#Contact" title="About"><span class="glyphicon glyphicon-earphone" title="Contact"></span></a></li>
                </ul>
                <noscript>
                    <div style="border: solid 1px #2FB73F; background: #FFFCDF; text-align:center;margin-left:30%">
                        <img src="~/Images/no.gif" width="25" height="25" alt="javascript disabled" />
                        <b style="font-size:large;color:red">JavaScript is disabled on your computer.</b> For complete view of this page it is necessary to enable JavaScript. Here are the <a href="http://www.enable-javascript.com" target="_blank"> instructions how to enable JavaScript in your web browser.</a>
                    </div>
                </noscript>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="Home">
        <div>
            <div>
                <h3>
                    PreScripds - Provides easy access to all your queries.
                </h3>
            </div>
        </div>
    </div>
    <div class="homeAboutbwn">
        <h2>Lorem Ipsum</h2>
    </div>
    <div id="About">
        <div>
            <div>
                <h2>About PreScripds</h2>
            </div>
        </div>
    </div>
    <div class="aboutContactbwn">
        <h2>Lorem Ipsum</h2>
    </div>
    <div id="Contact">
        <div>
            <div>
                <h2>Contact Us for further details</h2>
            </div>
        </div>
    </div>
    <div id="other">
        <div>
            <h2>Lorem Ipsum</h2>
            @RenderBody()
        </div>
    </div>
    @Html.Partial("Partials/_Footer")

    @{ Html.RenderAction("AppSettings", "Base"); }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
@{
    <script type="text/javascript">
        $(document).ready(function () {
            $('a[href*=#]').each(function () {
                if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '')
                && location.hostname == this.hostname
                && this.hash.replace(/#/, '')) {
                    var $targetId = $(this.hash), $targetAnchor = $('[name=' + this.hash.slice(1) + ']');
                    var $target = $targetId.length ? $targetId : $targetAnchor.length ? $targetAnchor : false;
                    if ($target) {
                        var targetOffset = $target.offset().top;
                        $(this).click(function () {
                            $("#nav li a").removeClass("active");
                            $(this).addClass('active');
                            $('html, body').animate({ scrollTop: targetOffset }, 5000);
                            return false;
                        });
                    }
                }
            });
        });
    </script>
}

PreScripds.UI/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/favicon.ico">
    <title>PreScripds</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/nav.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/Content/clndr.css" type="text/css" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div>
                    <a class="navbar-brand" href="@Url.Action("Index")">
                        <img src="~/Images/logo_532279_web.jpg" alt="prescripds" title="prescripds" />
                    </a>
                </div>

            </div>

            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                @*<div class="wrap" style="margin-top:7%;">
                    <div class="header">
                        <div class="header_top">*@
                <div class="sidebar-nav">
                    @Html.Partial("Partials/_Menu")
                    <div class="clear"></div>
                </div>
                @*<  </div>*@
            </div>
            <div class="main">
                <div class="wrap">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>


    </div>
    @Html.Partial("Partials/_Footer")

    @{ Html.RenderAction("AppSettings", "Base"); }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dashboard")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="~/Scripts/responsive-nav.js"></script>
    <script src="~/Scripts/ajax.js"></script>

</body>
</html>

PreScripds.UI/Views/Shared/_OpenLayout.cshtml
@using PreScripds.UI.Common;
<!DOCTYPE html>
<html>
<head>
    <title>PreScripds</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/favicon.ico">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <noscript>For full functionality of this page it is necessary to enable JavaScript. Here are the <a href="http://www.enable-javascript.com" target="_blank"> instructions how to enable JavaScript in your web browser</a></noscript>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @*<script src="~/Scripts/jquery-2.1.0.js"></script>*@
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">

        $(document).ready(function () {
            window.onbeforeunload = function () {
                return "Are you sure you wish to leave this page?";
            };
            $(window).unload(function () {
                document.getElementById('logoutForm').submit();
            });
        });

    </script>
</head>
<body class="openHtmlBg">
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div>
                        <a class="navbar-brand" href="@Url.Action("Index","Home")">
                            <img src="~/Images/logo_532279_web.jpg" alt="prescripds" title="prescripds" />
                        </a>
                    </div>

                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="@Url.Action("Index","Home")" title="Home"><span class="glyphicon glyphicon-home" title="Home"></span></a></li>
                        @if (SessionContext.CurrentUser != null)
                        {
                            <li style="color:#65C6C3 ; margin-top:6%">
                                Namaste! @SessionContext.CurrentUser.UserLogins.First().UserName &nbsp;
                            </li>
                            <li>
                                <a href="javascript:document.getElementById('logoutForm').submit()" title="Sign Out">
                                    <span class="glyphicon glyphicon-log-out"></span>
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </div>
    }
    <div class="container body-content" style="margin-top:7%">
        @if (SessionContext.SuspiciousErrorMessage != null)
        {
            <p style="color:red;background-color:white;padding:1%">@SessionContext.SuspiciousErrorMessage</p>
        }

        @RenderBody()
    </div>
    @Html.Partial("Partials/_Footer")
    @{ Html.RenderAction("AppSettings", "Base"); }
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/ajax.js"></script>
    @RenderSection("scripts", required: false)
    @Html.ProgressBar()
    <script src="~/Scripts/Common.js"></script>
</body>

</html>